### ISSUE TITLE
mock strstr（c++） 的时候报错 unresolved overloaded function type 

### ISSUE THREAD

**Issue by acgcc12** [wangyongfeng5/lmock#3]
![image](https://user-images.githubusercontent.com/39529988/140886906-81f19826-c687-45fe-aaf3-cdd09d925c47.png)

**Comment by wangyongfeng5** [comment]
貌似编译器有什么限制，总是无法直接得到strstr的地址，可以这样规避一下：

mock(dlsym(dlopen(nullptr, RTLD_NOW), "strstr"), mock_strstr);

注意需要添加头文件：dlfcn.h
可连接库文件 -ldl

**Comment by acgcc12** [comment]
> 貌似编译器有什么限制，总是无法直接得到strstr的地址，可以这样规避一下：
> 
> mock(dlsym(dlopen(nullptr, RTLD_NOW), "strstr"), mock_strstr);
> 
> 注意需要添加头文件：dlfcn.h 可连接库文件 -

> 貌似编译器有什么限制，总是无法直接得到strstr的地址，可以这样规避一下：
> 
> mock(dlsym(dlopen(nullptr, RTLD_NOW), "strstr"), mock_strstr);
> 
> 注意需要添加头文件：dlfcn.h 可连接库文件 -ldl
感谢

**Comment by acgcc12** [comment]
感谢
